// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucwtlswkljvansfbslvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjd3Rsc3drbGp2YW5zZmJzbHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTI5NjQsImV4cCI6MjA2MTY4ODk2NH0.GuLGVPFKxRvpN8b9ePOMgt1MfPTPUGE2K9bdB6TY3K8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);